const Sequelize = require('sequelize');

const Record = global.sequelize.define('record', {
  model: {
    type: Sequelize.ENUM(
      'Event',
      'Stack',
      'News',
      'Client',
      'HeaderImage',
      'Subscription',
      'Contact',
      'Auth',
      'Report',
      'Miscellaneous',
    ),
    allowNull: false,
  },
  target: {
    type: Sequelize.INTEGER,
  },
  operation: Sequelize.ENUM(
    'create',
    'update',
    'destroy',
  ),
  action: Sequelize.ENUM(
    'createEvent',
    'updateEventStatus',
    'updateEventDetail',
    'createEventHeaderImage',
    'updateEventHeaderImage',
    'createStack',
    'updateStackStatus',
    'updateStackDetail',
    'invalidateStack',
    'notifyNewStack',
    'createNews',
    'updateNewsStatus',
    'updateNewsDetail',
    'notifyNewNews',
    'createSubscription',
    'updateSubscription',
    'cancelSubscription',
    'addContactToSubscription',
    'removeSubscriptionContact',
    'createClient',
    'updateClientRole',
    'updateClientDetail',
    'updateClientPassword',
    'createClientVerificationToken',
    'authorizeThirdPartyAccount',
    'unauthorizeThirdPartyAccount',
    'notify',
    'sendEmailDailyReport',
    'sendWeeklyDailyReport',
    'sendMonthlyDailyReport',
  ),
  before: Sequelize.JSONB,
  data: Sequelize.JSONB,
}, {
  freezeTableName: true,
});

module.exports = Record;
